<?php

namespace Database\Seeders;

use App\Models\Player;
use Illuminate\Database\Seeder;

class PlayerSeeder extends Seeder
{
    public function run(): void
    {
        $players = [
            // VALORANT
            [
                'pseudo' => 'Minny',
                'first_name' => 'Minny',
                'last_name' => '',
                'game_name' => 'Valorant',
                'player_number' => '01',
                'role' => 'Duelist',
                'description' => 'Spécialiste des duels et des entrées de site.',
                'twitch' => null,
                'youtube' => '',
                'twitter' => '',
                'instagram' => 'vanyak',
                'is_streaming' => false,
                'profile_picture_uuid' => 'neptune',
            ],
            [
                'pseudo' => 'Marteen',
                'first_name' => 'Marteen',
                'last_name' => '',
                'game_name' => 'Valorant',
                'player_number' => '02',
                'role' => 'Controller',
                'description' => 'Expert en utilitaires et coordination de l’équipe.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => 'vanyak',
                'instagram' => '',
                'is_streaming' => false,
                'profile_picture_uuid' => 'marteen',
            ],
            [
                'pseudo' => 'Bipo',
                'first_name' => 'Bipo',
                'last_name' => '',
                'game_name' => 'Valorant',
                'player_number' => '03',
                'role' => 'Sentinel',
                'description' => 'Joueur défensif fiable avec un excellent positionnement.',
                'twitch' => 'skyrroztv',
                'youtube' => 'vanyak',
                'twitter' => 'vanyak',
                'instagram' => '',
                'is_streaming' => false,
                'profile_picture_uuid' => 'bipo',
            ],
            [
                'pseudo' => 'Glyph',
                'first_name' => 'Glyph',
                'last_name' => '',
                'game_name' => 'Valorant',
                'player_number' => '04',
                'role' => 'Flex',
                'description' => 'Polyvalent et capable de s’adapter à tous les rôles.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => 'vanyak',
                'instagram' => '',
                'is_streaming' => false,
                'profile_picture_uuid' => 'glyph-pic',
            ],
            [
                'pseudo' => 'Starxo',
                'first_name' => 'Starxo',
                'last_name' => '',
                'game_name' => 'Valorant',
                'player_number' => '05',
                'role' => 'Duelist',
                'description' => 'Agresseur de site, spécialiste des frags rapides.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => 'vanyak',
                'instagram' => '',
                'is_streaming' => false,
                'profile_picture_uuid' => 'starxo',
            ],

            // FORTNITE
            [
                'pseudo' => 'Pollo',
                'first_name' => 'Pollo',
                'last_name' => '',
                'game_name' => 'Fortnite',
                'player_number' => '20',
                'role' => 'Builder / Editor',
                'description' => 'Expert en constructions rapides et mécaniques précises.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => 'vanyak',
                'instagram' => 'vanyak',
                'is_streaming' => false,
                'profile_picture_uuid' => 'pollo',
            ],
            [
                'pseudo' => 'Vanyak',
                'first_name' => 'Vanyak',
                'last_name' => '',
                'game_name' => 'Fortnite',
                'player_number' => '21',
                'role' => 'IGL',
                'description' => 'Capitaine stratégique et joueur polyvalent.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => 'vanyak',
                'instagram' => 'vanyak',
                'is_streaming' => false,
                'profile_picture_uuid' => 'vanyak',
            ],
            [
                'pseudo' => 'Merstach',
                'first_name' => 'Merstach',
                'last_name' => '',
                'game_name' => 'Fortnite',
                'player_number' => '22',
                'role' => 'Duelist',
                'description' => 'Rapide et agressif, excelle en solo et duo.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => '',
                'instagram' => 'vanyak',
                'is_streaming' => false,
                'profile_picture_uuid' => 'merstach',
            ],
            [
                'pseudo' => 'Akira',
                'first_name' => 'Akira',
                'last_name' => '',
                'game_name' => 'Fortnite',
                'player_number' => '23',
                'role' => 'Support',
                'description' => 'Polyvalent, bon en rotations et soutien d’équipe.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => '',
                'instagram' => 'vanyak',
                'is_streaming' => false,
                'profile_picture_uuid' => 'akira',
            ],
            [
                'pseudo' => 'Marius',
                'first_name' => 'Marius',
                'last_name' => '',
                'game_name' => 'Fortnite',
                'player_number' => '24',
                'role' => 'Flex',
                'description' => 'Adaptable à tous les rôles et situations.',
                'twitch' => null,
                'youtube' => '',
                'twitter' => 'vanyak',
                'instagram' => '',
                'is_streaming' => false,
                'profile_picture_uuid' => 'marius',
            ],

            // CALL OF DUTY
            [
                'pseudo' => 'Neptune',
                'first_name' => 'Neptune',
                'last_name' => '',
                'game_name' => 'Call of Duty',
                'player_number' => '30',
                'role' => 'Assault',
                'description' => 'Spécialiste de la précision et des rotations rapides.',
                'twitch' => 'vanyak',
                'youtube' => 'vanyak',
                'twitter' => 'vanyak',
                'instagram' => '',
                'is_streaming' => false,
                'profile_picture_uuid' => 'neptune',
            ],
            [
                'pseudo' => 'Ghosty',
                'first_name' => 'Ghosty',
                'last_name' => '',
                'game_name' => 'Call of Duty',
                'player_number' => '31',
                'role' => 'SMG',
                'description' => 'Rapide et agressif, excelle en close combat.',
                'twitch' => 'vanyak',
                'youtube' => 'vanyak',
                'twitter' => 'vanyak',
                'instagram' => 'vanyak',
                'is_streaming' => false,
                'profile_picture_uuid' => 'ghosty',
            ],
            [
                'pseudo' => 'Envoy',
                'first_name' => 'Envoy',
                'last_name' => '',
                'game_name' => 'Call of Duty',
                'player_number' => '32',
                'role' => 'Flex',
                'description' => 'Adaptable à tous les rôles, très stratégique.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => 'vanyak',
                'instagram' => 'vanyak',
                'is_streaming' => false,
                'profile_picture_uuid' => 'envoy',
            ],
            [
                'pseudo' => 'Sib',
                'first_name' => 'Sib',
                'last_name' => '',
                'game_name' => 'Call of Duty',
                'player_number' => '33',
                'role' => 'Support',
                'description' => 'Joueur positionnel et soutien d’équipe fiable.',
                'twitch' => 'vanyak',
                'youtube' => '',
                'twitter' => 'vanyak',
                'instagram' => '',
                'is_streaming' => false,
                'profile_picture_uuid' => 'sib',
            ],

            // ROCKET LEAGUE
            [
                'pseudo' => 'Oski',
                'first_name' => 'Oski',
                'last_name' => '',
                'game_name' => 'Rocket League',
                'player_number' => '40',
                'role' => 'Striker',
                'description' => 'Joueur offensif, excellent en scoring.',
                'twitch' => null,
                'youtube' => '',
                'twitter' => '',
                'instagram' => '',
                'is_streaming' => false,
                'profile_picture_uuid' => 'oski',
            ],
            [
                'pseudo' => 'Nass',
                'first_name' => 'Nass',
                'last_name' => '',
                'game_name' => 'Rocket League',
                'player_number' => '41',
                'role' => 'All-rounder',
                'description' => 'Vision du jeu exceptionnelle et passes décisives.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => '',
                'instagram' => 'vanyak',
                'is_streaming' => false,
                'profile_picture_uuid' => 'nass',
            ],
            [
                'pseudo' => 'Archie',
                'first_name' => 'Archie',
                'last_name' => '',
                'game_name' => 'Rocket League',
                'player_number' => '42',
                'role' => 'Defender',
                'description' => 'Pilier défensif de l’équipe, sauvetages clutch.',
                'twitch' => null,
                'youtube' => 'vanyak',
                'twitter' => '',
                'instagram' => 'vanyak',
                'is_streaming' => true,
                'profile_picture_uuid' => 'archie',
            ]
        ];

        foreach ($players as $player) {
            Player::create($player);
        }
    }
}
