name: Build and Deploy Docker Image

on:
  push:
    branches: [ 'dev' ]

jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GH_PASSWORD }} | docker login ghcr.io -u requena-sam --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/requena-sam/easymates:latest

      - name: Dokploy Deployment
        uses: benbristow/dokploy-deploy-action@0.2.2
        with:
          api_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
          service_type: application
